### ISSUE TITLE
Xcode 6.4 编译不通过o(╯□╰)o

### ISSUE THREAD

**Issue by ZhangMingNan** [johnlui/Pitaya#1]
Xcode 6.4 编译不通过o(╯□╰)o

![snip20150804_1](https://cloud.githubusercontent.com/assets/5511046/9055697/c9eb718e-3abf-11e5-98e8-4e2b025f3341.png)

**Comment by johnlui** [comment]
Notice: https://github.com/johnlui/Pitaya#requirements

**Comment by johnlui** [comment]
## Requirements
- iOS 8.0+
- Xcode 6.4 (Swift 1.2) in v0.2.3
- Xcode 7 (Swift 2.0) after v0.3
