### ISSUE TITLE
请问怎么自定义请求错误信息？

### ISSUE THREAD

**Issue by abellee** [johnlui/Pitaya#17]
Pitaya Error:  The network connection was lost.

这个在哪里能自定义成中文吗？

**Comment by johnlui** [comment]
这个是 NSURLSession 抛出的，你可以自己检测 response 里的 status code 然后自己处理

**Comment by abellee** [comment]
@johnlui onNetworkError里的回调回传的error里好像没有response这个字段耶

**Comment by johnlui** [comment]
我试了一下，status code 是 error 的，我记错了。。。
也就是说你可以通过判断 error.code 来进行特殊处理。

**Comment by abellee** [comment]
@johnlui ok 谢谢 一个是我在simulator下因为是英文的 所以显示了英文 在真机上中文环境的话 好像显示的是中文 不过所有的错误都可以通过command+点击 NSURLErrorTimedOut 这个跳转过去后查看到
