### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by kuangtao22** [johnlui/Pitaya#18]
请教一下，上传文件时候，接口要求提交的参数：client_type、token、class_id、file，然后我的写法如下，但返回结果告诉我说file参数为空，请问正确的写法应该是怎么样的？求大神指导一下
比如：
let file = File(name: "file", data: imageData, type: "png")
let url = Interface_YiStore + "StoreCenter_Album.Images"

var params = ["client_type": ios, "token": AppPublic().userData.token]
params.updateValue(String(id), forKey: "id")

let pita = Pita.build(HTTPMethod: .POST, url: url).addFiles([file]).addParams(params)
pita.onNetworkError({ (error) in
print("error:(error.localizedDescription)")
})
pita.responseJSON { (json, response) in
print(json)
}

**Comment by johnlui** [comment]
我看一下

**Comment by kuangtao22** [comment]
好的

**Comment by kuangtao22** [comment]
大神，我的写法有问题吗？

**Comment by johnlui** [comment]
我刚刚补充了使用data生成 File 对象的测试代码，没有问题。你可以尝试看一下 imageData 是否是空的，如果还有问题可以尝试使用 Charles 监听一下 HTTP 请求，看看请求里面到底带没带图片，不排除是后端问题。

**Comment by kuangtao22** [comment]
imageData不为空，但是传到后端后，后端接收不到图片，请问下后端应该用什么方式接收图片

**Comment by johnlui** [comment]
后端直接使用表单形式接收就可以

**Comment by kuangtao22** [comment]
大神，经过多番测试，还是不行，服务端接收不到文件，然后我查了其他的网络处理工具类，
比如CharlinFeng、AFNetworking，发现他们的flie
`UploadFile(key: "file", data: data, mimeType: imageExtension, name: fileName)`或者是`formData.appendPartWithFileData(data, name: "file", fileName: fileName, mimeType: String(format: "image/%@", imageExtension))`
多了一个类型提交，这两个测试可以上传，
还有就是大神可不可以写个像CharlinFeng一样显示文件上传进度的功能

**Comment by johnlui** [comment]
懂了，我没有指定文件类型是不是图片，而是只表明了这是文件，所有后端在取图片的时候取不到。

解决办法有两个：

1. 让后端用取文件的方式获取图片
2. 修改 Pitaya 源码，加入图片参数。欢迎贡献代码呦~
