### ISSUE TITLE
public func addParams(params: [String: AnyObject]) -> Pitaya这个方法怎么发送json数据呀？

### ISSUE THREAD

**Issue by jackson1st** [johnlui/Pitaya#6]
在af当中都是直接在params当中写入要发送的json数据
但这个好像不行呀？

**Comment by johnlui** [comment]
是，需要自己生成 JSON：https://github.com/johnlui/Pitaya/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3#http-raw-body

**Comment by jackson1st** [comment]
嗯，我也是放在那里面了，菜鸟问一下，那加入参数，这个方法通常是做什么用的呀。一开始以为是传数据用的

**Comment by johnlui** [comment]
你去稍微了解一下 HTTP 协议就明白了，超级简单。

**Comment by jackson1st** [comment]
soga，看来得去看那本图解http了。上次买了，还没去瞅
